DELETE FROM PERSON;
INSERT INTO PERSON (NAME, ACTING) VALUES ('Ragnar', 2);
INSERT INTO PERSON (NAME, ACTING) VALUES ('Lagertha', 4);
INSERT INTO PERSON (NAME, ACTING) VALUES ('Bjorn', 3);
INSERT INTO PERSON (NAME, ACTING) VALUES ('Floki', 5);
INSERT INTO PERSON (NAME, ACTING) VALUES ('Rolla', 5);
INSERT INTO PERSON (NAME, ACTING) VALUES ('Ecbert', 7);
commit;