CREATE TABLE PERSON(
	ID INTEGER NOT NULL CONSTRAINT PK_PERSON PRIMARY KEY,
	NAME VARCHAR(256) NOT NULL CONSTRAINT UK_PERSON_NAME UNIQUE,
	ACTING INTEGER NOT NULL CONSTRAINT UK_PERSON_ACTING CHECK(ACTING>=0 AND ACTING<=10)
);

CREATE SEQUENCE SEQ_PERSON_ID START WITH 1;

CREATE OR REPLACE TRIGGER PERSON_BEFORE BEFORE INSERT ON PERSON FOR EACH ROW WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID:=SEQ_PERSON_ID.NEXTVAL;
END;
/

CREATE TABLE LOCATION(
	ID INTEGER NOT NULL CONSTRAINT PK_LOCATION PRIMARY KEY,
	NAME VARCHAR(256) NOT NULL CONSTRAINT UK_LOCATION_NAME UNIQUE
);

CREATE SEQUENCE SEQ_LOCATION_ID START WITH 1;

CREATE OR REPLACE TRIGGER LOCATION_BEFORE BEFORE INSERT ON LOCATION FOR EACH ROW WHEN (NEW.ID IS NULL)
BEGIN
  :NEW.ID:=SEQ_LOCATION_ID.NEXTVAL;
END;
/

CREATE TABLE PERSON_WAS_IN_LOCATION(
	PERSON_ID INTEGER NOT NULL CONSTRAINT FK_PERSLOC_PERSON REFERENCES PERSON ON DELETE CASCADE,
	LOCATION_ID INTEGER NOT NULL CONSTRAINT FK_PERSLOC_LOCATION REFERENCES LOCATION ON DELETE CASCADE
);